services:
  chemical-machines:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: chemical-machines
    runtime: nvidia
    # user: "${UID:-1000}:${GID:-1000}"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - NODE_ENV=development
    ports:
      - "3000:3000"      # cm-view web interface
      - "5173:5173"      # cm-view web interface
      - "5432:5432"      # PostgreSQL
      - "9200:9200"      # Elasticsearch
    volumes:
      - ./:/app

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

